# Generated by Django 4.1.5 on 2023-04-24 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_alter_recipe_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='weight',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='weight',
            new_name='quantity',
        ),
    ]
